### OneHotEncoder()
##### converting categorical features into numbers

In [29]:
import pandas as pd


car_sales = pd.read_csv('car-sales-extended.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [60]:
# car_sales.isna()
car_sales.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [30]:
# split the data into X and y

x = car_sales.drop('Price', axis = 1, inplace = False)
y = car_sales['Price']

### OneHotEncoder()

In [32]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ['Make', 'Colour', 'Doors']

transformer = ColumnTransformer([('one-hot', OneHotEncoder(), categorical_features)],
                                 remainder='passthrough')


transformed_x = transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]], shape=(1000, 13))

In [34]:
transformed_x = pd.DataFrame(transformed_x)
transformed_x

      0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100)

x_train, x_test, y_train, y_test = train_test_split(transformed_x, y, test_size=0.2)

model.fit(x_train, y_train)

RandomForestRegressor()

In [37]:
model.predict(x_test)

array([19269.11, 13363.3 , 43267.24, 11863.26, 10260.74, 17264.98,
       31140.93, 10791.74, 29743.53, 14116.59,  6563.77, 10912.93,
       12688.6 ,  8558.17, 15695.17, 29216.99, 18174.77, 11341.21,
       21348.27, 14460.73,  9172.67, 29125.36, 14773.16, 16391.14,
        9280.04, 15618.31, 15870.44, 20658.26, 22014.77, 13610.52,
       13971.98, 20871.39, 19478.27, 21904.49, 21422.4 , 11319.79,
        5574.72,  6773.84, 10933.24, 25244.63, 19876.66, 12581.43,
       19023.4 , 43809.3 , 14319.07,  8924.96,  7732.21, 19579.98,
       14915.84, 20475.71, 13807.71, 21001.83,  9099.08, 14153.07,
        9183.02, 10252.  , 14207.6 , 11507.75, 28903.67, 11003.67,
        6894.01,  7859.87,  8975.27, 16444.65, 15081.57, 11339.8 ,
       12145.94, 15566.53, 13930.52, 10019.56, 21989.22, 17046.46,
       20679.15, 21560.88, 20233.  , 12528.76, 25239.04,  9444.6 ,
       13629.22, 20160.36,  8601.26,  7499.74, 12807.84,  8861.72,
        9166.59, 10031.61,  8951.5 , 10490.99, 19325.75, 13242.86,
       11953.82, 26248.21, 19610.07, 27062.53, 14556.22, 11570.63,
       24072.69, 21559.71, 10509.91,  6880.12, 23541.62, 15362.77,
       13454.27,  9677.16, 16273.17, 13191.61, 29128.35, 15512.87,
       13219.94, 11117.05, 11064.19,  7171.02, 10675.97, 12880.65,
       20680.27, 11381.52, 18928.48, 14526.77, 20115.28, 13715.51,
       14922.48, 14994.05, 10886.3 , 18189.13, 17359.05,  9171.7 ,
       22888.56, 18672.97, 24703.79, 15120.24, 15886.09, 10248.3 ,
       21511.58, 22537.16, 12635.84, 16051.22, 22513.71, 16373.23,
        8788.06, 15537.83, 17324.96, 27161.23, 23725.97, 23801.46,
       11015.76, 28421.48, 16282.96, 13756.  , 15787.36, 23091.26,
        9930.8 ,  8425.79, 11284.71, 14778.17, 16304.04,  8875.23,
        9958.88, 17568.6 , 17047.91, 12439.86, 11277.49, 13208.74,
        8012.09, 38494.67, 14122.81, 16129.57, 14877.15, 24501.61,
       16810.16, 12003.23, 19018.11,  8669.33, 23091.35, 10226.23,
       11641.11, 16130.56, 17068.01, 14391.79, 10453.1 , 15777.84,
       14876.87, 14047.69, 16003.07, 19191.6 , 13267.69, 29574.13,
       11083.43, 16257.84,  7997.06, 17048.29, 15574.12, 11747.93,
       12989.81, 10245.82, 29529.07, 20422.22, 29216.99, 36434.68,
       12579.53, 24112.97])

In [39]:
model.score(x_test, y_test)

0.24763488200944195

#### Predicting on new Data

In [ ]:
df2 = pd.DataFrame(
    {
        'Make': ['Toyota', 'Honda'],
        'Colour': ['Red', 'Blue'],
        'Odometer (KM)': [150000, 80000],
        'Doors': [4, 3]
    }
)

transformed_df2 = transformer.transform(df2)
predictions = model.predict(transformed_df2)
predictions

array([11045.38, 19499.55])