In [2]:
#  pd.concat()

import pandas as pd
df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas"],
                    'Fee' : [20000,25000,22000,24000]})

df1 = pd.DataFrame({'Courses': ["Pandas","Hadoop","Hyperion","Java"],
                    'Fee': [25000,25200,24500,24900]})

# Using pandas.concat() to concat two DataFrames
data = [df, df1]
df2 = pd.concat(data)
print(df2)

    Courses    Fee
0     Spark  20000
1   PySpark  25000
2    Python  22000
3    pandas  24000
0    Pandas  25000
1    Hadoop  25200
2  Hyperion  24500
3      Java  24900

In [3]:
# Using pandas.concat() to Join Two DataFrames
# axis = 1 on column label
# join = 'inner'

df = pd.DataFrame({'Courses':["Spark","PySpark","Python","pandas"],
                      'Fee' :[20000,25000,22000,24000]})
  
df1 = pd.DataFrame({'Duration':['30day','40days','35days','60days'],
                      'Discount':[1000,2300,2500,2000,]}) 

df2 = pd.concat([df, df1], axis = 1, join = 'inner')
df2

   Courses    Fee Duration  Discount
0    Spark  20000    30day      1000
1  PySpark  25000   40days      2300
2   Python  22000   35days      2500
3   pandas  24000   60days      2000

In [4]:
df2 = pd.concat([df, df1])
df2

   Courses      Fee Duration  Discount
0    Spark  20000.0      NaN       NaN
1  PySpark  25000.0      NaN       NaN
2   Python  22000.0      NaN       NaN
3   pandas  24000.0      NaN       NaN
0      NaN      NaN    30day    1000.0
1      NaN      NaN   40days    2300.0
2      NaN      NaN   35days    2500.0
3      NaN      NaN   60days    2000.0