In [1]:
# drop() method is used to remove the columns from the DataFrame
# returns a new DataFrame after dropping the columns specified with the drop method.
# to remove columns on the existing DataFrame object use inplace=True param

In [20]:

# Create DataFrame
import pandas as pd
technologies = ({
    'Courses':["Spark","PySpark","Hadoop","Python","pandas","Oracle","Java"],
    'Fee' :[20000,25000,26000,22000,24000,21000,22000],
    'Duration':['30day', '40days' ,'35days', '40days', '60days', '50days', '55days']
              })
df = pd.DataFrame(technologies)
df

   Courses    Fee Duration
0    Spark  20000    30day
1  PySpark  25000   40days
2   Hadoop  26000   35days
3   Python  22000   40days
4   pandas  24000   60days
5   Oracle  21000   50days
6     Java  22000   55days

In [21]:
# drop() - Drop Columns

df2 = df.drop(['Fee'], axis = 1)
df2

   Courses Duration
0    Spark    30day
1  PySpark   40days
2   Hadoop   35days
3   Python   40days
4   pandas   60days
5   Oracle   50days
6     Java   55days

In [22]:
df2 = df.drop(['Fee', 'Duration'], axis = 1)
df2

   Courses
0    Spark
1  PySpark
2   Hadoop
3   Python
4   pandas
5   Oracle
6     Java

In [23]:
#  Drop Column by Index

df2 = df.drop(df.columns[[1]], axis = 1)
df2

   Courses Duration
0    Spark    30day
1  PySpark   40days
2   Hadoop   35days
3   Python   40days
4   pandas   60days
5   Oracle   50days
6     Java   55days

In [15]:
df2 = df.drop(df.columns[[0,1]], axis = 1)
df2

  Duration
0    30day
1   40days
2   35days
3   40days
4   60days
5   50days
6   55days

In [24]:
df.drop(['Fee', 'Duration'], axis = 1, inplace = True)
df

   Courses
0    Spark
1  PySpark
2   Hadoop
3   Python
4   pandas
5   Oracle
6     Java

In [25]:
df

   Courses
0    Spark
1  PySpark
2   Hadoop
3   Python
4   pandas
5   Oracle
6     Java