In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = { 'Company' : ['Facebook','Google','Microsoft','Facebook','Google','Google','Microsoft','Facebook','Microsoft'],
         'Person'  : ['Sam', 'Ram', 'Amy', 'Carl', 'Sarah', 'Mohan', 'Mahesh', 'Uma', 'Ajit'],
         'Sales'   : [200, 130, 160, 300, 500, 450, 600, 100, 50]   
}

df = pd.DataFrame(data)

In [ ]:
df

## groupby

In [7]:
groupByComp = df.groupby('Company')

In [10]:
# perform Aggregate functions

groupByComp.sum()

C:\Users\ak8184\AppData\Local\Temp\ipykernel_10092\2347075331.py:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupByComp.sum()

           Sales
Company
Facebook     600
Google      1080
Microsoft    810

In [11]:
groupByComp.mean()

C:\Users\ak8184\AppData\Local\Temp\ipykernel_10092\158940053.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupByComp.mean()

           Sales
Company
Facebook   200.0
Google     360.0
Microsoft  270.0

In [12]:
groupByComp.std()

C:\Users\ak8184\AppData\Local\Temp\ipykernel_10092\2309165305.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groupByComp.std()

                Sales
Company
Facebook   100.000000
Google     200.748599
Microsoft  291.032644

In [13]:
groupByComp.max()

           Person  Sales
Company
Facebook      Uma    300
Google      Sarah    500
Microsoft  Mahesh    600

In [14]:
groupByComp.min()

          Person  Sales
Company
Facebook    Carl    100
Google     Mohan    130
Microsoft   Ajit     50

In [19]:
df.groupby('Company').describe()

          Sales
          count   mean         std    min    25%    50%    75%    max
Company
Facebook    3.0  200.0  100.000000  100.0  150.0  200.0  250.0  300.0
Google      3.0  360.0  200.748599  130.0  290.0  450.0  475.0  500.0
Microsoft   3.0  270.0  291.032644   50.0  105.0  160.0  380.0  600.0

In [ ]:
df.describe()